apiVersion: v1
kind: Service
metadata:
  name: mariadb-leocinema-svc
  namespace: leocinema
  labels:
    db: mariadb-leocinema
    tier: db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    db: mariadb-leocinema
    tier: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: leocinema
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: leocinema
spec:
  serviceName: mariadb-leocinema-svc
  replicas: 1
  selector:
    matchLabels:
      db: mariadb-leocinema
      tier: db
  template:
    metadata:
      labels:
        db: mariadb-leocinema
        tier: db
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:latest
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "leoborges3005"
            - name: MARIADB_DATABASE
              value: "leocinemadb"
            - name: MARIADB_USER
              value: "leocinemauser"
            - name: MARIADB_PASSWORD
              value: "leocinemapass"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
