apiVersion: v1
kind: Service
metadata:
  name: mariadb-leocinema-svc
  namespace: leocinema
  labels:
    db: mariadb-leocinema
    tier: db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    db: mariadb-leocinema
    tier: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: leocinema
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    CREATE USER 'leocinemauser'@'%' IDENTIFIED BY 'leocinemapass';
    CREATE DATABASE leocinemadb;
    GRANT ALL PRIVILEGES ON leocinemadb.* TO 'leocinemauser'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: leocinema
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: leocinema
spec:
  serviceName: mariadb-leocinema-svc
  replicas: 1
  selector:
    matchLabels:
      db: mariadb-leocinema
      tier: db
  template:
    metadata:
      labels:
        db: mariadb-leocinema
        tier: db
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "leoborges3005"
      volumes:
      - name: config
        configMap:
          name: mariadb-config
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
